name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened!
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
      
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Import OmniKey from...
        2. Call method...
        3. See error...
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide:
        - Node.js version
        - Bun version
        - omni-transactions-sdk version
        - Operating system
      placeholder: |
        - Node.js: v20.x.x
        - Bun: v1.x.x
        - omni-transactions-sdk: v0.x.x
        - OS: Ubuntu 22.04
    validations:
      required: true